service: <%= serviceName %>

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: ${env:ENVIRONMENT}
  timeout: 6
  memorySize: 128
  environment:
    ENVIRONMENT: ${self:provider.stage}

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  func:
    handler: src/handler.handle
