service: ${file(./package.json):name}

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${opt:stage, env:ENVIRONMENT}
  timeout: 15
  memorySize: 128
  environment:
    ENVIRONMENT: ${self:provider.stage}
  tags:
    ENVIRONMENT: ${self:provider.stage}
    PROJECT: ${self:service.name}

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude: [aws-sdk]

functions:
  func:
    handler: src/handler.handle
